= Connection hints

label:new[Introduced in bolt 4.3]

As of bolt version 4.3, the server may optionally include a set of configuration hints within the `SUCCESS` metadata provided in response to the `HELLO` message.
Drivers may choose to interpret or ignore these hints at their own discretion.
The following set of hints are currently defined.


[[hint-ssr-enabled]]
== ssr.enabled::Boolean
label:new[Introduced in bolt 5.8]

Indicates if the database cluster is configured with Server Side Routing (SSR) enabled, so transactions can be routed between members of the cluster if the current member is able to process it. 

SSR should be considered disabled in the absence of this hint.

.Example
[source, Bolt]
----
C: HELLO {"user_agent":"neo4j-javascript/5.26.0","bolt_agent":{"product":"neo4j-javascript/5.26.0","platform":"darwin 24.1.0; arm64","language_details":"Node/18.19.0 (v8 10.2.154.26-node.28)"}}
S: SUCCESS {"server": "Neo4j/5.26.0", "connection_id": "example-connection-id:1", "hints": {"ssr.enabled": true}}
----

[[hint-telemetry-enabled]]
== telemetry.enabled::Boolean
label:new[Introduced in bolt 5.4]

Whether telemetry collection via xref:bolt/message.adoc#messages-telemetry[`TELEMETRY` message] is enabled.

If `false` or not present, drivers should not send `TELEMETRY` messages.
The server will ignore them, should they be sent nonetheless.

.Example
[source, Bolt]
----
C: HELLO {"user_agent": "Example/5.13.0", "scheme": "basic", "principal": "test", "credentials": "test"}
S: SUCCESS {"server": "Neo4j/5.13.0", "connection_id": "example-connection-id:1", "hints": {"telemetry.enabled": true}}
----


[[hint-recv-timeout-seconds]]
== connection.recv_timeout_seconds::Integer
label:new[Introduced in bolt 4.3]

Maximum amount of time (in seconds) for which a connection may remain idle following a request before drivers should consider it stale.

The server will ensure that a chunk (or `NOOP` chunk) will be transmitted at least once per timeout period. Drivers which choose to interpret this hint may terminate connections which are considered stale by the definition of this hint.

.Example
[source, Bolt]
----
C: HELLO {"user_agent": "Example/4.0.0", "scheme": "basic", "principal": "test", "credentials": "test"}
S: SUCCESS {"server": "Neo4j/4.3.0", "connection_id": "example-connection-id:1", "hints": {"connection.recv_timeout_seconds": 120}}
----
