name: "CLA Check"

on:
  pull_request_target:
    branches:
      - main
      - dev

jobs:
  cla-check:
    if: github.event.pull_request.user.login != 'renovate[bot]'

    runs-on: ubuntu-latest

    env:
      PULL_REQUEST_NUMBER: ${{ github.event.number }}
      CHECKS_TOKEN: ${{ secrets.DOCS_CHECKS_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: neo-technology/whitelist-check
          token: $CHECKS_TOKEN
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run CLA check
        shell: bash

        run: |
          owner=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f1)
          repository=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f2)

          ./bin/examine-pull-request "$owner" "$repository" "$CHECKS_TOKEN" "$PULL_REQUEST_NUMBER" cla-database.csv
        